server:
  port: 8081
  id: server-1
spring:
  application:
    name: WebSoketService
  kafka:
    bootstrap-servers: ${KAFKA_CONN_BS:127.0.0.1:19092}
    topic: 'massage-chanel'
    consumer:
      group: 'massage-subscriber'

  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6371}

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.simp: DEBUG
